platform :ios, '10.0'

target 'PeerConnectionApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBApp
  pod 'ALBPeerConnection', :path => '../ALBPeerConnection'
  pod 'ALBNoSQLDB', :path => '../../ALBNoSQLDB/ALBNoSQLDB'
end
